# Generated by Django 4.2.7 on 2024-03-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='Createed_date',
            new_name='Created_date',
        ),
    ]
