# Generated by Django 4.2.7 on 2024-03-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_createed_date_content_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='Created_date',
            new_name='created_date',
        ),
    ]
