# Generated by Django 4.2.7 on 2024-04-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_created_date_content_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('-created_date',)},
        ),
    ]
