# Generated by Django 4.2.7 on 2024-01-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_titel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titel',
            field=models.CharField(max_length=250),
        ),
    ]
